defaults: &defaults
  adapter: sqlite

sqlite: &sqlite
  adapter: sqlite

postgres: &postgres
  adapter: postgres
  host: localhost
  user: sapphire
  password:

mysql: &mysql
  adapter: mysql
  host: localhost
  user: sapphire
  password:

persevere: &persevere
  adapter: persevere
  versioned: true
  host: localhost
  port: 8080

development:
  <<: *defaults
  path: db/sqlite3/development.sqlite3
  repositories:
    collection_data:
      <<: *mysql
      database: sapphire_development
    yogo_persevere:
      <<: *persevere

test:
  path: db/sqlite3/test.sqlite3
  <<: *defaults
  repositories:
    collection_data:
      <<: *mysql
      database: sapphire_test
    yogo_persevere:
      <<: *persevere
      port: 8081

production:
  path: db/sqlite3/production.sqlite3
  <<: *defaults
  repositories:
    collection_data:
      <<: *mysql
      database: sapphire_production
    yogo_persevere:
      <<: *persevere

