defaults: &defaults
  adapter: sqlite

sqlite: &sqlite
  adapter: sqlite

postgres: &postgres
  adapter: postgres
  host: localhost

mysql: &mysql
  adapter: mysql
  host: localhost
  user: crux
  password:

persevere: &persevere
  adapter: persevere
  versioned: true
  host: localhost
  port: 8080

development:
  database: db/sqlite3/development.sqlite3
  <<: *defaults
  repositories:
    collection_data:
      <<: *mysql
      database: crux_development
    yogo_persevere:
      <<: *persevere

test:
  database: db/sqlite3/test.sqlite3
  <<: *defaults
  repositories:
    collection_data:
      <<: *postgres
      database: crux_test
    yogo_persevere:
      <<: *persevere
      port: 8081

production:
  database: db/sqlite3/production.sqlite3
  <<: *defaults
  repositories:
    collection_data:
      <<: *postgres
      database: crux_production
    yogo_persevere:
      <<: *persevere

